[DEV] Support multiple targets
cpb-/yocto-cooker pull request #106
Opened 2022-02-08 09:55 UTC by Louson

Enable the build of several targets in the same build directory. The field
'target' in the menu can be a single string or an array of string. If given an
array, all entries will be built (the build order is undefined).

This does not affect the previous 'target' behaviour.

2022-02-08 09:56 UTC, Louson commented
Linked to issue #103

2022-02-08 10:12 UTC, Louson commented
An undefined behavior remains concerning the inheritance:

### Inherit from a virtual build configuration an set a bitbake target

This removes the virtual bitbake target

### Inherit from a normal build configuration and set a bitbake target

This removes previous targets, but maybe we want to merge them ?

### Inherit from multiple virtual build configurations

Should we merge all bitbake targets ?

### Inherit from multiple build configurations with at least one non virtual

Should we merge all non virtual bitbake targets ?

2022-02-08 23:49 UTC, pboettch requested changes

2022-02-08 23:49 UTC, pboettch commented on cooker/cooker.py
> +            self.targets_.append(target)
```suggestion
            self.targets_ = [target]
```

2022-02-08 23:49 UTC, pboettch commented on cooker/cooker.py
> +            if len(build.targets_) > 0:
Pythonic way of checking list emptiness.

```suggestion
            if build.targets_:
```

2022-02-08 23:49 UTC, pboettch commented on cooker/cooker.py
> +                build_info = ' (bakes {})'.format(build.targets())
I'd prefer to not simply dump the list, but generate a comma-separated string. `', '.join(build.targets())`

2022-02-08 23:54 UTC, pboettch commented
> An undefined behavior remains concerning the inheritance:
> ### Inherit from a virtual build configuration an set a bitbake target
> 
> This removes the virtual bitbake target
> ### Inherit from a normal build configuration and set a bitbake target
> 
> This removes previous targets, but maybe we want to merge them ?
> ### Inherit from multiple virtual build configurations
> 
> Should we merge all bitbake targets ?
> ### Inherit from multiple build configurations with at least one non virtual
> 
> Should we merge all non virtual bitbake targets ?

I think targets should be overridden by the final build. As you have done your implementation.

Parent build-targets have most like no sens in this inherited build-configuration. At least not for image-targets. 

What is actually your use-case? What are the multiple targets you are building within one build-config/build-dir using the same local.conf and thus machine.conf etc. I only can think of non-image-targets. Please enlighten us.

2022-02-09 20:47 UTC, Louson commented
Well, there is nothing I want to do with inheritance. I was just wondering.

In my case I am creating training courses. I will use the beaglebone for all projects. I'd like to build them all together.

2022-02-10 10:59 UTC, pboettch commented
After discussing with @cpb- we understood that currently the target-field is overwritten if a parent has it. Your patch does the same with list of targets. So it's fine, let's discuss this in another thread or issue if this needs a change.

2022-02-10 11:01 UTC, pboettch approved these changes

2022-02-10 11:07 UTC, Louson commented
Yes, same machine.conf, same local.conf, same layers

2022-02-10 11:37 UTC, pboettch commented
Just with different package selections, or something different?

2022-02-10 14:15 UTC, merged