config: add migration-code for cookerconfig-files
cpb-/yocto-cooker pull request #125
Opened 2022-06-08 16:30 UTC by pboettch

Now the .cookerconfig-file contains an API-version. This enables
cooker to migrate from one config-version to another in existing
work-directories when the cooker-version has been switched.

Fixes #124

2022-06-09 06:43 UTC, cpb- requested changes

2022-06-09 06:43 UTC, cpb- commented on cooker/cooker.py
> +
On my current `.cookerconfig`, I don't have `cooker-config-version` (of course). So `config_version` is `0`.
But I already have `"sstate-dir": "sstate-cache"`. I think it would be better to keep the previous `self.cfg['sstate-dir']` if present, and fill it with `self.DEFAULT_CONFIG['sstate-dir']` only if it is undefined.

2022-06-09 06:43 UTC, cpb- commented on test/basic/config/cookerconfig-version-0
> +}
Add a test with a previous `"sstate-dir"` line.

2022-06-09 06:43 UTC, cpb- commented on test/basic/config/cookerconfig-version-0
> +}
Add a test with a previous `"sstate-dir"` line.

2022-06-09 06:48 UTC, pboettch commented on cooker/cooker.py
> +
Nice catch!

2022-06-15 14:24 UTC, pboettch commented
@cpb- I fixed your requested changes

2022-06-15 16:55 UTC, cpb- approved these changes

2022-06-15 16:55 UTC, merged