[DEV] menu path can be absolute or relative
cpb-/yocto-cooker pull request #128
Opened 2022-09-23 10:07 UTC by Louson

When the menu path given in the command init (or cook) started with '/', its absolute path is stored (after symlinks resolution). If not, its path relative to the .cookerconfig is stored (after symlinks resolution).

The aim is to enable to initialize and download the sources in a host machine and build in a container which may have a different location.

2022-09-23 16:50 UTC, cpb- approved these changes

2022-09-23 20:16 UTC, pboettch commented
Hmm, good idea. I think we should always store a relative path to the menu in the config-file. Or is there a reason for strong full-paths?

I think we should realpath it (to resolved symlinks) and then store as relative path.

The inconvenience I see is that cooker initialized dir cannot be moved anymore as it would not find the menu any longer.

2022-09-23 21:20 UTC, Louson commented
My reason would be to not work against the user. If an absolute path is given in arguments, there is no reason to make it relative and it might be confusing.

2022-09-24 18:01 UTC, pboettch commented
I see your point. In my usage experience I actually don't remember when and how I ran `cooker init` when using my projects because I basically never use init (and cook) which need a menu.

Ok for letting the user choose, but how to inform the user about this choice and why which choice is better than the other and if which circumstances?

Updating the README? At least.

2022-09-25 12:37 UTC, Louson commented
Here is a suggestion for the README

2022-09-25 14:46 UTC, cpb- approved these changes

2022-09-25 15:55 UTC, pboettch requested changes
I think we need tests for this feature. I know, I'm quite demanding.

2022-09-25 15:55 UTC, pboettch commented on cooker/cooker.py
> +            self.cfg['menu'] = os.path.relpath(menu_file)
Does this work? `relpath` needs a second argument to the source path IIRC.

2022-09-25 15:55 UTC, pboettch commented on cooker/cooker.py
> +        if menu_file[0] == '/':
Please use menu_file.startswith()

2022-09-25 16:41 UTC, cpb- commented on cooker/cooker.py
> +            self.cfg['menu'] = os.path.relpath(menu_file)
The second parameter defaults to `os.curdir`

2022-09-25 16:57 UTC, pboettch commented on cooker/cooker.py
> +            self.cfg['menu'] = os.path.relpath(menu_file)
OK, works when we do init (because we cannot change the target-dir yet), but not when doing cook from, for example  build-dir, or does it?

2022-09-26 20:25 UTC, Louson commented on cooker/cooker.py
> +            self.cfg['menu'] = os.path.relpath(menu_file)
strangely, I tested with two different directories. Let me check tomorrow what was wrong in my test

2022-09-27 12:12 UTC, pboettch approved these changes

2022-09-27 12:12 UTC, pboettch commented
Great job!

2022-09-27 12:12 UTC, merged