Add overridden distro configuration for poky
cpb-/yocto-cooker pull request #137
Opened 2023-02-06 12:15 UTC by ycongal-smile

- Add function to get the overridden distro configuration if it exists
- Add rule in schema to allow to add a new entry in menu
- Add test case for an overridden distro

This is needed for a somewhat exotic setup : When you clone the individual Yocto repo instead of the poky.git combo-layer (Which is easier in order to contribute upstream). In this case the cloned repos can't have the same layout as poky.git.

Note: Ever is the author of the patches, I've reviewed them and will handle the PR from here (Ever has agreed. I hope that's OK)

2023-02-17 09:19 UTC, ycongal-smile commented
Hi @cpb- @pboettch "gentle ping" on this PR.
I'm afraid you missed it...?
Any way I can help you review/merge this?

2023-02-19 13:50 UTC, cpb- approved these changes

2023-02-19 13:51 UTC, cpb- approved these changes

2023-02-21 17:08 UTC, pboettch requested changes

2023-02-21 17:08 UTC, pboettch commented on cooker/cooker-menu-schema.json
> +            "items": {
Please be specific by specifying the expected properties with  `"additionalProperties": false`. The goal of the schema is to validate the menu to avoid unnecessary if's in the code.

2023-02-23 09:26 UTC, ycongal-smile commented on cooker/cooker-menu-schema.json
> +            "items": {
Thanks!
We updated the PR.

2023-02-23 09:28 UTC, pboettch approved these changes
Very good, thanks for your contribution.

2023-02-23 09:28 UTC, merged