Add support for executing a command in a poky-initialized shell
cpb-/yocto-cooker pull request #146
Opened 2023-07-26 09:34 UTC by ycongal-smile

PR initially from @amine-smile : https://github.com/cpb-/yocto-cooker/pull/145.

Updated the shell command to support executing a command within the poky-initialized shell. Introduced optional positional arguments, which allows users to specify a command to be executed (similar to what ssh does).  When a command argument is provided, it is executed within the shell environment.

Example: `cooker shell <cooker-build>  'bitbake -c cve_check <package-name>'`

The unittest was added : Only check the generated command line with dry-run. Actually testing that the command run correctly would require cloning a poky environment.

And, also, a minor gitignore improvement.

2023-07-26 13:48 UTC, cpb- approved these changes

2023-07-26 15:00 UTC, pboettch commented
Does leaving out the single quotes also work? (Sorry to insist)

`cooker shell <cooker-build>  bitbake -c cve_check <package-name>`

This is the reason I insisted on using `nargs='*'` .

Why, because I want to avoid extensive quote-escaping: `cooker shell ... 'command \'arg with space in  quote\''`, but rather tell cooker shell to use all arguments after the build as sub-command and its arguments.

2023-07-26 15:40 UTC, pboettch commented
It might be we have to use `--` to separate args to cooker-shell and args for the sub-command.

2023-07-26 16:02 UTC, ycongal-smile commented
> It might be we have to use `--` to separate args to cooker-shell and args for the sub-command.

It is :
```
 $ cooker shell qemu-x86-64 -- bitbake-getvar -r bash --value SUMMARY
An sh-compatible command language interpreter
```

I've updated the PR with a better (and working) example and a mention of this feature in the README.

2023-07-26 20:42 UTC, cpb- commented
A useful example could also be

```
cooker shell qemu-x86-64 runqemu nographic
```

This is what I will use during training courses 🙂.

Le mer. 26 juil. 2023, 18:02, Yoann Congal ***@***.***> a
écrit :

> It might be we have to use -- to separate args to cooker-shell and args
> for the sub-command.
>
> It is :
>
>  $ cooker shell qemu-x86-64 -- bitbake-getvar -r bash --value SUMMARY
> An sh-compatible command language interpreter
>
> I've updated the PR with a better (and working) example and a mention of
> this feature in the README.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cpb-/yocto-cooker/pull/146#issuecomment-1652106024>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB5U3E2YSE6WEE4L5PB2I6TXSE5RRANCNFSM6AAAAAA2YJUAXE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-07-28 16:26 UTC, ycongal-smile commented
> A useful example could also be 
> ```
> cooker shell qemu-x86-64 runqemu nographic
> ``` 
> This is what I will use during training courses.

Added :)

2023-07-29 23:10 UTC, pboettch requested changes

2023-07-29 23:10 UTC, pboettch commented on cooker/cooker.py
> +            str_cmd = " ".join(cmd)
Doing this we lose the escaping done by subprocess_run when you give an array as argument. And I think it won't work for string containing spaces.

    cooker shell <build> -- something -c "to do" 

will be executed as

   something -c to do

.

2023-07-29 23:10 UTC, pboettch commented on cooker/cooker.py
> +    def shell(self, build_names: List[str], cmd: str = None):
with `from typing import List, Optional` on top.

```suggestion
    def shell(self, build_names: List[str], cmd: Optional[List[str]] = None):
```

2023-07-29 23:10 UTC, pboettch commented on cooker/cooker.py
> +        if len(cmd) >= 1:
isn't it always an array, even though only on cmd is given with nargs='*'?

2023-07-29 23:10 UTC, pboettch commented on test/basic/shell/test
> +cooker --dry-run shell qemu echo test >>output.txt
```suggestion
cooker --dry-run shell qemu echo test >>output.txt
cooker --dry-run shell qemu echo "test with spaces and quites \"" >>output.txt
```

Should give 

```
/bin/sh -c source /layers/poky/oe-init-build-env /builds/build-qemu > /dev/null || exit 1; echo "test with spaces and quites \""
```

2023-07-30 16:31 UTC, ycongal-smile commented on cooker/cooker.py
> +            str_cmd = " ".join(cmd)
You are right! Fixed by switching to [shlex.join](https://docs.python.org/3/library/shlex.html#shlex.join)

2023-07-30 16:40 UTC, ycongal-smile commented on cooker/cooker.py
> +        if len(cmd) >= 1:
> isn't it always an array, even if only one cmd is given with nargs='*'?

Yes, always an array : 
```
$ cooker --debug shell qemu-x86-64
cmd=[]

 $ cooker --debug shell qemu-x86-64 one_command
cmd=['one_command']

 $ cooker --debug shell qemu-x86-64 two command
cmd=['two', 'command']
```

Should I change something?

2023-07-30 16:58 UTC, ycongal-smile commented
Updated following @pboettch review

2023-07-30 17:04 UTC, ycongal-smile commented on cooker/cooker.py
> +        if len(cmd) >= 1:
I guess either `cmd`  is Optional and I should check it for None in shell() (line 774) and filter it line 1024

OR

`cmd` is not `Optional` and I should remove the `Optional` type and keep the length check

?

2023-07-31 09:40 UTC, pboettch commented on cooker/cooker.py
> +        if len(cmd) >= 1:
Yes, remove the `Optional`.  It was a mistake.

2023-08-01 14:03 UTC, ycongal-smile commented on cooker/cooker.py
> +        if len(cmd) >= 1:
Removed!

2023-08-01 14:04 UTC, ycongal-smile commented
Removed Optional (https://github.com/cpb-/yocto-cooker/pull/146#discussion_r1279051000)

2023-08-01 14:35 UTC, pboettch approved these changes

2023-08-01 14:35 UTC, merged